---
# To overwrite a specific section of common_properties, add the desired property with a new value after the '<<: *common_properties' line in the corresponding section

common_properties: &common_properties
  security_alerts: true
  exclude_labels:
    - WIP
    - ignore
  use_labels: true
  exclude_titles:
    - DO NOT MERGE
    - PROTOTYPE
    - WIP
    - DNM
    - DRAFT
    - PARKED
  quotes_days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

mtvh-online:
  channel: '#slack-bot-testing'
  <<: *common_properties
  repos:
    - mytvh-web
    - mytvh-mid
    - mytvh-pay
    - mtvh-formio
