name: Run Tests
# on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies and run Rake
      run: |
        bundle install
        bundle exec rake
